# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/noryx
spring.datasource.username=noryx
spring.datasource.password=noryx

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Virtual Threads
spring.threads.virtual.enabled=true

# Server
server.port=8080